### ISSUE TITLE
No implementation for method init and register

### ISSUE THREAD

**Issue by Vayth** [benediktdreher/azure_notification_hubs#5]
I tried using the package on a new project. However I got exception on init and register method.
`MissingPluginException (MissingPluginException(No implementation found for method init on channel azure_notification_hubs))`

`MissingPluginException (MissingPluginException(No implementation found for method register on channel azure_notification_hubs))`

I tried cloning the git and run the example, but faced with the same error.
Is there something I did wrong?

Flutter 1.12.13+hotfix8

**Comment by ghost** [comment]
Hello, the exact steps I did to run the example are:

```
git clone https://github.com/Sally-Assistant/azure_notification_hubs.git
```

Fill in `NHInfoConnectionString` and `NHInfoHubName` in the `azure_notification_hubs/example/lib/main.dart`.

```
cd azure_notification_hubs/example
flutter run
```

Then I was able to register/unregister. Is there any additional error info you can provide, perhaps some compilation error due to missing packages? Could you try running `flutter pub get` in the top-level directory?

Kind regards.

**Comment by Vayth** [comment]
Just making sure, Infohubname and connectionstring are this, right? just in case it's misconfiguration on my part

![notifhub](https://user-images.githubusercontent.com/41632555/77519570-50612800-6eb2-11ea-849e-416acc11c91a.png)

This is the log from my debug console
[errorlog.txt](https://github.com/Sally-Assistant/azure_notification_hubs/files/4379925/errorlog.txt)

**Comment by Vayth** [comment]
I apologize, I just re-read the readme carefully once again and see that this is ios only at the moment. Maybe that's why it couldn't find the method.

Looking forward for android support :)
